### ISSUE TITLE
suggestion: tests

### ISSUE THREAD

**Issue by iuioiua** [supabase-community/deno-fresh-openai-doc-search#13]
I suggest breaking up functionality into smaller functions and testing each function using [Deno's in-built test runner](https://deno.land/manual@v1.32.5/basics/testing). This might be overkill if the codebase doesn't need to be so robust.

**Comment by thorwebdev** [comment]
Yah, might be nice to show how to do that, but not super high priority I'd say.

**Comment by iuioiua** [comment]
I'll close this for now. We can explore if it develops into a greater priority.
