### ISSUE TITLE
suggestion: create a Deno Deploy project

### ISSUE THREAD

**Issue by iuioiua** [supabase-community/deno-fresh-openai-doc-search#8]
Doing this and linking to this repo when creating a project will enable preview deployments to be automatically created upon each commit to a non-forked PR. This way, the behaviour of PRs and the main branch can be remotely validated.

See https://deno.com/deploy

**Comment by iuioiua** [comment]
Are you able to do this, @thorwebdev?

**Comment by thorwebdev** [comment]
✅  sorry for the delay https://supabase-openai-doc-search.deno.dev/
